# Copyright 2023, Phillip Heller
#
# This file is part of Prodigy Reloaded.
#
# Prodigy Reloaded is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General
# Public License as published by the Free Software Foundation, either version 3 of the License, or (at your
# option) any later version.
#
# Prodigy Reloaded is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even
# the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License along with Prodigy Reloaded. If not,
# see <https://www.gnu.org/licenses/>.

functions = {
    0: 'NO_EVENT',
    1: 'ADD_TEXT',
    2: 'ADD_TEXT_AND_FIELD_END',
    3: 'BACKSPACE',
    4: 'DELETE_TEXT',
    5: 'TOGGLE_INSERT',
    6: 'HELP',
    7: 'INSERT_TEXT',
    8: 'FIELD_HELP',
    9: 'PAGE_HELP',
    10: 'NAVIGATION',
    11: 'INTERFIELD_CURSOR',
    12: 'NEXT',
    13: 'BACK',
    14: 'PATH',
    15: 'JUMP',
    16: 'ACTION',
    17: 'FIELD_END',
    18: 'ELEMENT_END',
    19: 'PAGE_END',
    20: 'BYE',
    21: 'LOGON',
    22: 'VIEWPATH',
    23: 'KEYWORD',
    24: 'GUIDE',
    25: 'RECALL',
    26: 'UNDO',
    27: 'WHERE',
    28: 'SRNPRT',
    29: 'SMFILE',
    30: 'SCAN',
    31: 'TOOLS',
    32: 'DIRECTORY',
    33: 'INDEX',
    34: 'FIND',
    35: 'LEAVE',
    36: 'ZIP',
    37: 'NEW_LINE',
    38: 'SCROLL_UP',
    39: 'SCROLL_DOWN',
    40: 'SET_CLOSE_WINDOW',
    41: 'SET_OPEN_WINDOW',
    42: 'CURSOR',
    43: 'LOGOFF',
    44: 'LOOK',
    45: 'TRAVEL',
    46: 'FIRST_PAGE',
    47: 'LAST_PAGE',
    48: 'PREVIOUS_MENU',
    49: 'LOGICAL_FUNCTIONS',
}

actions = {
    16: 'DISABLE',
    32: 'FILTER',
    64: 'FILTER_ON',
    00: 'NORMAL'
}

gevs = {
    1: 'SYS_RETURN_CODE',
    2: 'SYS_API_EVENT',
    3: 'SYS_LOGICAL_KEY',
    5: 'SYS_TONE_PULSE',
    6: 'SYS_LINE_STATUS',
    7: 'SYS_KEYWORD_LENGTH',
    9: 'SYS_SCROLL_INCREMENT',
    10: 'SYS_CURRENT_FIELD',
    11: 'SYS_DATE',
    12: 'SYS_TIME',
    13: 'SYS_CURRENT_PAGE',
    14: 'SYS_SELECTED_OBJ_ID',
    15: 'SYS_NAVIGATE_OBJ_ID',
    16: 'SYS_SCROLL_ROW',
    17: 'SYS_SCROLL_COL',
    18: 'SYS_PATH',
    19: 'SYS_TTX_PHONE',
    20: 'SYS_TOTAL_PAGES',
    21: 'SYS_PAGE_NUMBER',
    22: 'SYS_BASE_OBJ_ID',
    23: 'SYS_WINDOW_ID',
    24: 'SYS_PATH_PTR',
    25: 'SYS_KEYWORDS',
    26: 'SYS_CURRENT_CURSOR_POS',
    27: 'SYS_CURRENT_BACKGROUND_COLOR',
    28: 'SYS_CURRENT_FOREGROUND_COLOR',
    29: 'SYS_HARDWARE_STATUS',
    30: 'SYS_NOCOMM',
    31: 'SYS_UM_DIA_HEADER',
    32: 'SYS_UM_MESSAGE_TEXT',
    33: 'SYS_CA_ERROR_TRACK_INFO',
    34: 'SYS_ASSISANT_CURRENT_INFO',
    35: 'SYS_SCREEN_DATA_TABLE',
    36: 'SYS_AD_LIST',
    37: 'SYS_CURRENT_KEYWORD',
    38: 'SYS_PREVIOUS_KEYWORD',
    39: 'SYS_GUIDE',
    40: 'SYS_PREVIOUS_MENU',
    41: 'SYS_PREVIOUS_SEEN_MENU',
    42: 'SYS_SCAN_LIST',
    43: 'SYS_SCAN_LIST_POINTER',
    44: 'SYS_PATH_NAME',
    45: 'SYS_NAVIGATE_KEYWORD',
    46: 'KEYWORD_TABLE',
    47: 'KEYWORD_DISP',
    48: 'KEYWORD_TABLE_ENTRY_LENGTH',
    49: 'KEYWORD_LENGTH',
    50: 'EXT_TABLE',
    51: 'SYS_DATA_COLLECT',
    52: 'SYS_FM0_TXHDR',
    53: 'SYS_FM0_TXDID',
    54: 'SYS_FM0_TXRID',
    55: 'SYS_FM4_TXHDR',
    56: 'SYS_FM4_TXUSEID',
    57: 'SYS_FM4_TXCORID',
    58: 'SYS_FM64_TXHDR',
    59: 'SYS_FM64_TXDATA',
    60: 'SYS_FM0_RXHDR',
    61: 'SYS_FM4_RXHDR',
    62: 'SYS_FM4_RXUSEID',
    63: 'SYS_FM4_RXCORID',
    64: 'SYS_FM64_RXHDR',
    65: 'SYS_FM64_RXDATA',
    66: 'SYS_SURROGATE',
    67: 'SYS_LEAVE',
    68: 'SYS_ZIP',
    69: 'SYS_INT_REGS',
    70: 'SYS_TTX_HELP_ID',
    71: 'SYS_SELECTOR_DATA',
    72: 'SYS_SELECTOR_PATH',
    73: 'SYS_LOGICAL_EVENT',
    74: 'SYS_USER_ID',
    75: 'SYS_HELP_APPL',
    76: 'SYS_HELP_HUB_APPL_PTO',
    77: 'SYS_ACCESS_KEY_OBJ_ID',
    78: 'SYS_WORD_WRAP',
    79: 'SYS_MESSAGING_STATUS',
    80: 'SYS_VERSION',
    81: 'SYS_LEADER_AD_ID',
    82: 'SYS_BAUD_RATE',
    83: 'SYS_COM_PORT',
    84: 'SYS_OBJ_HEADER',
    85: 'SYS_SESSION_STATUS',
    86: 'SYS_FETCH_RETURN',
    90: 'SYS_COMMAND_LINE',
    258: 'PRF_BA_FIRST_LINE',
    259: 'PRF_BA_2ND_LINE',
    260: 'PRF_BA_CITY',
    261: 'PRF_BA_STATE',
    262: 'PRF_BA_ZIPCODE',
    263: 'PRF_RES_TELEPHONE',
    270: 'PRF_ENABLED_DATE',
    271: 'PRF_DISABLED_DATE',
    272: 'PRF_DISABLED_REASON',
    273: 'PRF_HOUSEHOLD_USERID',
    274: 'PRF_SUBSCRIBER_SUFFIX',
    275: 'PRF_HOUSEHOLD_PASSWORD',
    276: 'PRF_HOUSEHOLD_INCM_RANGE_CODE',
    277: 'PRF_SUFFIX_IN_USE_INDICATORS',
    278: 'PRF_ACCOUNT_STATUS_FLAG',
    282: 'PRF_USER_ITEM_LAST_A',
    283: 'PRF_USER_ITEM_FIRST_A',
    284: 'PRF_USER_ITEM_MIDDLE_A',
    285: 'PRF_USER_ITEM_TITLE_A',
    287: 'PRF_ACCESS_LEVEL_A',
    288: 'PRF_INDICATORS_A',
    291: 'PRF_USER_ITEM_LAST_B',
    292: 'PRF_USER_ITEM_FIRST_B',
    293: 'PRF_USER_ITEM_MIDDLE_B',
    294: 'PRF_USER_ITEM_TITLE_B',
    296: 'PRF_ACCESS_LEVEL_B',
    297: 'PRF_INDICATORS_B',
    300: 'PRF_USER_ITEM_LAST_C',
    301: 'PRF_USER_ITEM_FIRST_C',
    302: 'PRF_USER_ITEM_MIDDLE_C',
    303: 'PRF_USER_ITEM_TITLE_C',
    305: 'PRF_ACCESS_LEVEL_C',
    306: 'PRF_INDICATORS_C',
    309: 'PRF_USER_ITEM_LAST_D',
    310: 'PRF_USER_ITEM_FIRST_D',
    311: 'PRF_USER_ITEM_MIDDLE_D',
    312: 'PRF_USER_ITEM_TITLE_D',
    314: 'PRF_ACCESS_LEVEL_D',
    315: 'PRF_INDICATORS_D',
    318: 'PRF_USER_ITEM_LAST_E',
    319: 'PRF_USER_ITEM_FIRST_E',
    320: 'PRF_USER_ITEM_MIDDLE_E',
    321: 'PRF_USER_ITEM_TITLE_E',
    323: 'PRF_ACCESS_LEVEL_E',
    324: 'PRF_INDICATORS_E',
    327: 'PRF_USER_ITEM_LAST_F',
    328: 'PRF_USER_ITEM_FIRST_F',
    329: 'PRF_USER_ITEM_MIDDLE_F',
    330: 'PRF_USER_ITEM_TITLE_F',
    332: 'PRF_ACCESS_LEVEL_F',
    333: 'PRF_INDICATORS_F',
    334: 'PRF_USER_PROFILE_USER_ID',
    335: 'PRF_PASSWORD',
    336: 'PRF_REGION',
    338: 'PRF_MAIL_COUNT',
    339: 'PRF_ACCESS_CONTROL',
    340: 'PRF_COUNT_PASSWORD_CHANGE_TRYS',
    341: 'PRF_PORT_INDEX_ID',
    342: 'PRF_INDIC_FOR_APPLICATION_USE',
    343: 'PRF_GENDER',
    345: 'PRF_DATE_USER_WAS_ENROLLED',
    346: 'PRF_DATE_USER_WAS_DELETED',
    347: 'PRF_REASON_FOR_DELETION',
    348: 'PRF_SOURCE_OF_DELETE',
    350: 'PRF_USER_LAST_NAME',
    351: 'PRF_USER_FIRST_NAME',
    352: 'PRF_USER_MIDDLE_NAME',
    353: 'PRF_USER_TITLE',
    354: 'PRF_DATE_OF_BIRTH',
    355: 'PRF_PREFERRED_SHOP_CARD',
    356: 'PRF_PREFERRED_TRAVEL_CARD',
    358: 'PRF_MARITAL_STATUS',
    359: 'PRF_USER_CREDIT_CARD_NUMBER_1',
    360: 'PRF_USER_CREDIT_CARD_EXP_1',
    361: 'PRF_USER_CREDIT_CARD_NAME_1',
    362: 'PRF_USER_CREDIT_CARD_NUMBER_2',
    363: 'PRF_USER_CREDIT_CARD_EXP_2',
    364: 'PRF_USER_CREDIT_CARD_NAME_2',
    365: 'PRF_USER_CREDIT_CARD_NUMBER_3',
    366: 'PRF_USER_CREDIT_CARD_EXP_3',
    367: 'PRF_USER_CREDIT_CARD_NAME_3',
    368: 'PRF_USER_CREDIT_CARD_NUMBER_4',
    369: 'PRF_USER_CREDIT_CARD_EXP_4',
    370: 'PRF_USER_CREDIT_CARD_NAME_4',
    371: 'PRF_BANK_PROVIDER_01',
    372: 'PRF_GATEWAY_ID_01',
    373: 'PRF_BANK_PROVIDER_USER_01',
    374: 'PRF_BANK_PROVIDER_02',
    375: 'PRF_GATEWAY_ID_02',
    376: 'PRF_BANK_PROVIDER_USER_02',
    377: 'PRF_BANK_PROVIDER_03',
    378: 'PRF_GATEWAY_ID_03',
    379: 'PRF_BANK_PROVIDER_USER_03',
    387: 'PRF_AA_ADVANTAGE_NUMBER',
    390: 'PRF_SEAT_CODE',
    394: 'PRF_TRAVEL_AGENT_CODE',
    395: 'PRF_PRFRD_TRAVEL_AGENT_INDIC',
    406: 'PRF_PC_MAKE_MODEL',
    407: 'PRF_MONITOR_MAKE_MODEL',
    408: 'PRF_MODEM_MAKE_MODEL',
    409: 'PRF_PRINTER_MAKE_MODEL',
    417: 'PRF_RESPONSE_TYPE_01',
    418: 'PRF_RESPONSE_TYPE_02',
    419: 'PRF_RESPONSE_TYPE_03',
    420: 'PRF_RESPONSE_TYPE_04',
    421: 'PRF_RESPONSE_TYPE_05',
    423: 'PRF_LEISURE_ACTIVITY_01',
    424: 'PRF_LEISURE_ACTIVITY_02',
    425: 'PRF_LEISURE_ACTIVITY_03',
    426: 'PRF_LEISURE_ACTIVITY_04',
    427: 'PRF_LEISURE_ACTIVITY_05',
    428: 'PRF_NUTRITION_DIET_INFO',
    436: 'PRF_MAIL_PURCHASE_PAST_YEAR',
    485: 'PRF_EDUCATION_CODE',
    496: 'PRF_R_GROUP_CODE',
    497: 'PRF_TYPE_OF_HOUSING',
    509: 'PRF_INDUSTRY',
    522: 'PRF_PERSONAL_PATH_JUMPWORD_13',
    523: 'PRF_PERSONAL_PATH_JUMPWORD_14',
    524: 'PRF_PERSONAL_PATH_JUMPWORD_15',
    525: 'PRF_PERSONAL_PATH_JUMPWORD_16',
    526: 'PRF_PERSONAL_PATH_JUMPWORD_17',
    527: 'PRF_PERSONAL_PATH_JUMPWORD_18',
    528: 'PRF_PERSONAL_PATH_JUMPWORD_19',
    529: 'PRF_PERSONAL_PATH_JUMPWORD_20',
    550: 'PRF_AIRLINE_MEAL_PREFERENCE',
    551: 'PRF_EAASY_SABRE_PASSWORD',
    552: 'PRF_AUTO_SKIP',
    555: 'PRF_KEYSTROKE_BUFFER',
    559: 'PRF_SOUND',
    562: 'PRF_USAGE_LEVEL',
    563: 'PRF_USER_ACCESS_TO_FULLFILL',
    564: 'PRF_RESELLER_NUMBER',
    565: 'PRF_RESELLER_NAME',
    566: 'PRF_RESELLER_CLASS',
    567: 'PRF_RESELLER_TYPE',
    568: 'PRF_USER_CLASS',
    569: 'PRF_BUS_CLIENT_CODE',
    570: 'PRF_USER_SECURITY_LEVEL',
    571: 'PRF_PERCENT_DISCOUNT',
    573: 'PRF_GAME_PROFILE',
    574: 'PRF_PREFERRED_TRAVEL_AGENT',
    575: 'PRF_PERSONAL_PATH_JUMPWORD_1',
    576: 'PRF_PERSONAL_PATH_JUMPWORD_2',
    577: 'PRF_PERSONAL_PATH_JUMPWORD_3',
    578: 'PRF_PERSONAL_PATH_JUMPWORD_4',
    579: 'PRF_PERSONAL_PATH_JUMPWORD_5',
    580: 'PRF_PERSONAL_PATH_JUMPWORD_6',
    581: 'PRF_PERSONAL_PATH_JUMPWORD_7',
    582: 'PRF_PERSONAL_PATH_JUMPWORD_8',
    583: 'PRF_PERSONAL_PATH_JUMPWORD_9',
    584: 'PRF_PERSONAL_PATH_JUMPWORD_10',
    585: 'PRF_PERSONAL_PATH_JUMPWORD_11',
    586: 'PRF_PERSONAL_PATH_JUMPWORD_12',
    587: 'PRF_ACCOUNT_STATUS',
    588: 'PRF_MAGAZINE_SUBSCRIPTION_01',
    589: 'PRF_MAGAZINE_SUBSCRIPTION_02',
    590: 'PRF_MAGAZINE_SUBSCRIPTION_03',
    591: 'PRF_MAGAZINE_SUBSCRIPTION_04',
    592: 'PRF_MAGAZINE_SUBSCRIPTION_05',
    593: 'PRF_PERSONALIZATION_01',
    594: 'PRF_PERSONALIZATION_02',
    595: 'PRF_PERSONALIZATION_03',
    596: 'PRF_PERSONALIZATION_04',
    597: 'PRF_PERSONALIZATION_05',
    598: 'PRF_BUYER_CODE',
    599: 'PRF_CREDIT_RATING',
    600: 'PRF_ACCT_REC_BAL',
    601: 'PRF_AMOUNT_ORDERED_TODAY',
    602: 'PRF_CREDIT_LIMIT',
    603: 'PRF_PREFERRED_CUSTOMER',
    604: 'PRF_NEW_NAME',
    605: 'PRF_CUG_ACCT_NUM',
    606: 'PRF_CATEGORY_01',
    607: 'PRF_CATEGORY_02',
    608: 'PRF_CATEGORY_03',
    609: 'PRF_CATEGORY_04',
    610: 'PRF_CATEGORY_05',
    611: 'PRF_GROUP_01',
    612: 'PRF_GROUP_02',
    613: 'PRF_GROUP_03',
    614: 'PRF_SECTION_01',
    615: 'PRF_SECTION_02',
    616: 'PRF_SECTION_03',
    617: 'PRF_PREVIEW_HELP',
    618: 'PRF_HOUSE_BILL_REF_NUM',
    619: 'PRF_HOUSE_CUG_ID',
    620: 'PRF_HOUSE_SERVICE_ID',
    621: 'PRF_HOUSE_EXP_DATE',
    622: 'PRF_HOUSE_GRAPH_ADAPTER',
    623: 'PRF_HOUSE_MSG_MEM_CLASS',
    624: 'PRF_HOUSE_OBJ_MEM_CLASS',
    625: 'PRF_HOUSE_GRAPH_ADAPTER_SC',
    626: 'PRF_HOUSE_PC_MAKE_SC',
    627: 'PRF_HOUSE_MODEM_SC',
    628: 'PRF_HOUSE_MONITOR_SC',
    629: 'PRF_HOUSE_PRINTER_SC',
    630: 'PRF_HOUSE_INCOME_SC',
    631: 'PRF_HOUSE_RES_PHONE',
    632: 'PRF_HOUSE_R_GROUP_SC',
    633: 'PRF_HOUSE_S_GROUP_SC',
    634: 'PRF_HOUSE_TYPE',
    635: 'PRF_HOUSE_USE_LEVEL',
    638: 'PRF_HOUSE_USER_CLASS',
    636: 'PRF_HOUSE_VERSION',
    637: 'PRF_S_GROUP_CODE',
    639: 'PRF_TIER_01_ENROLL_DATE',
    640: 'PRF_ACTIVE_TRADER',
    641: 'PRF_BROKER_ACCOUNT',
    642: 'PRF_BROKER_MEMBER',
    643: 'PRF_CUG_SERVICE_ID',
    644: 'PRF_CAMPAIGN_CODE',
    645: 'PRF_FAST_PATH_FULFILL',
    646: 'PRF_UNIQUE_IDENTIFIER',
    647: 'PRF_MSG_MEM_CLASS',
    648: 'PRF_OBJ_MEM_CLASS',
    649: 'PRF_OCCUP_CODE',
    650: 'PRF_PROMO_DATE',
    651: 'PRF_PROMO_OFFER_CODE',
    652: 'PRF_PROMO_RESP_METHOD',
    653: 'PRF_PROMO_RESP_TYPE',
    654: 'PRF_DATE_OF_BIRTH_SC',
    655: 'PRF_EDUCATION_CODE_SC',
    656: 'PRF_GENDER_SC',
    657: 'PRF_INDUSTRY_CODE_SC',
    658: 'PRF_OCCUPATION_CODE_SC',
    659: 'PRF_MARITIAL_STATUS_SC',
    660: 'PRF_MAIL_PURCHASE_SC',
    661: 'PRF_SIGNATURE_ON_FILE',
    662: 'PRF_TRAVEL_TEL_NUM',
    663: 'PRF_TC_BA_FIRST_LINE',
    664: 'PRF_TC_BA_2ND_LINE',
    665: 'PRF_TC_BA_CITY',
    666: 'PRF_TC_BA_STATE',
    667: 'PRF_TC_BA_ZIPCODE',
    668: 'PRF_VERSION',
    669: 'PRF_BANK_01_ENABLED',
    670: 'PRF_BANK_01_DISABLED',
    671: 'PRF_BANK_02_ENABLED',
    672: 'PRF_BANK_02_DISABLED',
    673: 'PRF_BANK_03_ENABLED',
    674: 'PRF_BANK_03_DISABLED',
    675: 'PRF_PASSPORT',
    676: 'PRF_GROCERY_PTR',
    677: 'PRF_ASK_EXPERT',
    678: 'PRF_CUG_ID',
    679: 'PRF_DRIVER_LIC_STATE',
    680: 'PRF_DRIVER_LIC_NUM',
    681: 'PRF_PAYMENT_CODE',
    682: 'PRF_PAYMENT_TEXT',
    683: 'PRF_GROCERY_CONTACT_PHONE',
    684: 'PRF_GROCERY_ITEM_COUNT',
    685: 'PRF_GROCERY_STORE_REF_NUM',
    686: 'PRF_GROCERY_MEMBER_STATUS',
    695: 'PRF_TIER_OF_SERVICE',
    696: 'PRF_CCL_VERSION_NUM',
    687: 'PRF_ML_DATE',
    688: 'PRF_ML_INDICATOR',
    698: 'PRF_SEL_STATUS',
    699: 'PRF_SEL_NUM_ITEMS',
    700: 'PRF_SEL_ITEM_LIST',
    701: 'PRF_SAVED_ORDER_DATE',
    702: 'PRF_SAVED_ORDER_STORE_NO',
    703: 'PRF_SAVED_ORDER_PTR',
    706: 'PRF_LAST_LOGON_DATE',
    708: 'PRF_LAST_LOGON_TIME',
    709: 'PRF_BANK1_GATEWAY_ID',
    710: 'PRF_BANK1_BANK_CODE',
    711: 'PRF_BANK1_STATE_CODE',
    712: 'PRF_BANK1_STATUS_CODE',
    713: 'PRF_BANK1_ENABLE_DATE',
    714: 'PRF_BANK1_DISABLE_DATE',
    715: 'PRF_BANK1_BILL_DATE',
    716: 'PRF_BANK1_CHARGE_CODE',
    717: 'PRF_BANK1_BANK_INFO1',
    718: 'PRF_BANK1_BANK_INFO2',
    719: 'PRF_BANK2_GATEWAY_ID',
    720: 'PRF_BANK2_BANK_CODE',
    721: 'PRF_BANK2_STATE_CODE',
    722: 'PRF_BANK2_STATUS_CODE',
    723: 'PRF_BANK2_ENABLE_DATE',
    724: 'PRF_BANK2_DISABLE_DATE',
    725: 'PRF_BANK2_BILL_DATE',
    726: 'PRF_BANK2_CHARGE_CODE',
    727: 'PRF_BANK2_BANK_INFO1',
    728: 'PRF_BANK2_BANK_INFO2',
    729: 'PRF_BANK3_GATEWAY_ID',
    730: 'PRF_BANK3_BANK_CODE',
    731: 'PRF_BANK3_STATE_CODE',
    732: 'PRF_BANK3_STATUS_CODE',
    734: 'PRF_BANK3_ENABLE_DATE',
    735: 'PRF_BANK3_DISABLE_DATE',
    736: 'PRF_BANK3_BILL_DATE',
    737: 'PRF_BANK3_CHARGE_CODE',
    738: 'PRF_BANK3_BANK_INFO1',
    739: 'PRF_BANK3_BANK_INFO2',
    740: 'PRF_BANK4_GATEWAY_ID',
    741: 'PRF_BANK4_BANK_CODE',
    742: 'PRF_BANK4_STATE_CODE',
    743: 'PRF_BANK4_STATUS_CODE',
    744: 'PRF_BANK4_ENABLE_DATE',
    745: 'PRF_BANK4_DISABLE_DATE',
    746: 'PRF_BANK4_BILL_DATE',
    747: 'PRF_BANK4_CHARGE_CODE',
    748: 'PRF_BANK4_BANK_INFO1',
    749: 'PRF_BANK4_BANK_INFO2',
    750: 'PRF_BANK5_GATEWAY_ID',
    751: 'PRF_BANK5_BANK_CODE',
    752: 'PRF_BANK5_STATE_CODE',
    753: 'PRF_BANK5_STATUS_CODE',
    754: 'PRF_BANK5_ENABLE_DATE',
    755: 'PRF_BANK5_DISABLE_DATE',
    756: 'PRF_BANK5_BILL_DATE',
    757: 'PRF_BANK5_CHARGE_CODE',
    758: 'PRF_BANK5_BANK_INFO1',
    759: 'PRF_BANK5_BANK_INFO2',
    763: 'PRF_MADMAZE_SAVE',
    766: 'PRF_MESSAGING_OPTIONS_FLD',
    767: 'PRF_AUTOLOGON_NICKNAME',
    31929: 'CUG_LOGON_CS',
    31930: 'ALT_PHONE_NUMBER',
    31931: 'APPL_VERS_CHECK',
    31932: 'SYS_LOGON_CHOICE',
    31933: 'SYS_DRIVERS_AVAIL',
    31934: 'AD_REVIEW_IDS',
    31935: 'SYS_ZIP_KEYWORD',
    31936: 'SYS_CURRENT_AD_LIST',
    31937: 'SYS_APPL_AD_LIST',
    31938: 'SYS_APPL_RANDOM',
    31939: 'SYS_DEFAULT_RANDOM',
    31980: 'TTX_ASST_ZIP_FLAG',
    31981: 'TTX_ASST_EVENT',
    31982: 'TTX_ASST_ZIPPABLE_PTO',
    31983: 'SYS_ZIP_SMPARM',
    31984: 'SYS_CURRENT_CATEGORY',
    31985: 'SYS_SAFE_PAGE',
    31986: 'SYS_SAFE_PAGE_2',
    31987: 'SYS_ERROR_TEXT',
    31988: 'SYS_QMENU_FLAGS',
    31989: 'SYS_REVIEW_KWS',
    31990: 'SYS_REVIEW_PTR',
    31991: 'STND_MENU_VAR10',
    31992: 'STND_MENU_VAR9',
    31993: 'STND_MENU_VAR8',
    31994: 'STND_MENU_VAR7',
    31995: 'STND_MENU_VAR6',
    31996: 'STND_MENU_VAR5',
    31997: 'STND_MENU_VAR4',
    31998: 'STND_MENU_VAR3',
    31999: 'STND_MENU_VAR2',
    32000: 'STND_MENU_VAR1'
}

# DEFINE RET_OK                      , '0'
# DEFINE RET_HARDWARE_ERROR          , '1'
# DEFINE RET_TIMEOUT                 , '2'
# DEFINE RET_BEYOND_EOF              , '3'
# DEFINE RET_PRINTER_OUT_OF_PAPER    , '4'
# DEFINE RET_OVERFLOW                , '5'
# DEFINE RET_UNDERFLOW               , '6'
# DEFINE RET_ZERO                    , '7'
# DEFINE RET_NOT_ZERO                , '8'
# DEFINE RET_ALL_ONES                , '9'
# DEFINE RET_SOME_ONES               ,'10'
# DEFINE RET_NO_ONES                 ,'11'
# DEFINE RET_NOT_OPEN                ,'13'
# DEFINE RET_NOT_FOUND               ,'14'
# DEFINE RET_DISK_FULL               ,'15'
# DEFINE RET_BAD_LENGTH              ,'16'
# DEFINE RET_BAD_POINTER             ,'17'
# DEFINE RET_END_OF_FILE             ,'18'
# DEFINE RET_STACK_EMPTY             ,'19'
# DEFINE RET_STACK_FULL              ,'20'
# DEFINE RET_NOT_ARRIVED             ,'21'
# DEFINE RET_ALPHA                   ,'22'
# DEFINE RET_INTEGER                 ,'23'
# DEFINE RET_DECIMAL                 ,'24'
# DEFINE RET_DIVIDE_BY_ZERO          ,'25'
# DEFINE RET_ALREADY_OPEN            ,'26'
# DEFINE RET_NOT_ENOUGH_SLOTS        ,'27'
# DEFINE DISABLE                    ,'16'
# DEFINE FILTER                     ,'32'
# DEFINE FILTER_ON                  ,'64'
# DEFINE NORMAL                     ,'00'
# DEFINE HI                         ,'1'
# DEFINE LO                         ,'0'
# DEFINE INPUT                      ,'r'
# DEFINE OUTPUT                     ,'w'
# DEFINE I_O                        ,'r+'
# DEFINE APPEND                     ,'a'
# DEFINE SYS_DELIMITER                ,'~'
# }
# DEFINE   NULL_KEY,          0
# DEFINE   TEXT_KEY,          1
# DEFINE   A_KEY,             2
# DEFINE   B_KEY,             3
# DEFINE   C_KEY,             4
# DEFINE   D_KEY,             5
# DEFINE   E_KEY,             6
# DEFINE   F_KEY,             7
# DEFINE   G_KEY,             8
# DEFINE   H_KEY,             9
# DEFINE   I_KEY,            10
# DEFINE   J_KEY,            11
# DEFINE   K_KEY,            12
# DEFINE   L_KEY,            13
# DEFINE   M_KEY,            14
# DEFINE   N_KEY,            15
# DEFINE   O_KEY,            16
# DEFINE   P_KEY,            17
# DEFINE   Q_KEY,            18
# DEFINE   R_KEY,            19
# DEFINE   S_KEY,            20
# DEFINE   T_KEY,            21
# DEFINE   U_KEY,            22
# DEFINE   V_KEY,            23
# DEFINE   W_KEY,            24
# DEFINE   X_KEY,            25
# DEFINE   Y_KEY,            26
# DEFINE   Z_KEY,            27
# DEFINE   LA_KEY,           28
# DEFINE   LB_KEY,           29
# DEFINE   LC_KEY,           30
# DEFINE   LD_KEY,           31
# DEFINE   LE_KEY,           32
# DEFINE   LF_KEY,           33
# DEFINE   LG_KEY,           34
# DEFINE   LH_KEY,           35
# DEFINE   LI_KEY,           36
# DEFINE   LJ_KEY,           37
# DEFINE   LK_KEY,           38
# DEFINE   LL_KEY,           39
# DEFINE   LM_KEY,           40
# DEFINE   LN_KEY,           41
# DEFINE   LO_KEY,           42
# DEFINE   LP_KEY,           43
# DEFINE   LQ_KEY,           44
# DEFINE   LR_KEY,           45
# DEFINE   LS_KEY,           46
# DEFINE   LT_KEY,           47
# DEFINE   LU_KEY,           48
# DEFINE   LV_KEY,           49
# DEFINE   LW_KEY,           50
# DEFINE   LX_KEY,           51
# DEFINE   LY_KEY,           52
# DEFINE   LZ_KEY,           53
# DEFINE   N0_KEY,           54
# DEFINE   N1_KEY,           55
# DEFINE   N2_KEY,           56
# DEFINE   N3_KEY,           57
# DEFINE   N4_KEY,           58
# DEFINE   N5_KEY,           59
# DEFINE   N6_KEY,           60
# DEFINE   N7_KEY,           61
# DEFINE   N8_KEY,           62
# DEFINE   N9_KEY,           63
# DEFINE   BACKSPACE_KEY,    64
# DEFINE   INSERT_KEY,       65
# DEFINE   DELETE_KEY,       66
# DEFINE   CURSOR_UP_KEY,    67
# DEFINE   CURSOR_DOWN_KEY,  68
# DEFINE   CURSOR_LEFT_KEY,  69
# DEFINE   CURSOR_RIGHT_KEY, 70
# DEFINE   TAB_LEFT_KEY,     71
# DEFINE   TAB_RIGHT_KEY,    72
# DEFINE   TAB_UP_KEY,       73
# DEFINE   TAB_DOWN_KEY,     74
# DEFINE   TAB_FORWARD_KEY,  75
# DEFINE   TAB_BACK_KEY,     76
# DEFINE   HOME_KEY,         77
# DEFINE   END_KEY,          78
# DEFINE   SCROLL_UP_KEY,    79
# DEFINE   SCROLL_DOWN_KEY,  80
# DEFINE   CLOSE_WINDOW_KEY, 81
# DEFINE   COMMIT_KEY,       82
# DEFINE   HELP_KEY,         83
# DEFINE   NEXT_KEY,         84
# DEFINE   BACK_KEY,         85
# DEFINE   PATH_KEY,         86
# DEFINE   SCAN_KEY,         87
# DEFINE   SPACE_BAR,        88
# DEFINE   PAGE_HELP_KEY,    89
# DEFINE   ACTION_KEY,       90
# DEFINE   VIEWPATH_KEY,     91
# DEFINE   GUIDE_KEY,        92
# DEFINE   INDEX_KEY,        93
# DEFINE   KEEP_KEY,         94
# DEFINE   PREVIOUS_MENU_KEY,95
# DEFINE   UNDO_KEY,         96
# DEFINE   PRT_KEY,          97
# DEFINE   JUMP_KEY,         98
# DEFINE   RESET_KEY,       255
# DEFINE NO_EVENT,           0
# DEFINE ADD_TEXT,           1
# DEFINE ADD_TEXT_AND_FIELD_END, 2
# DEFINE BACKSPACE,          3
# DEFINE DELETE_TEXT,        4
# DEFINE TOGGLE_INSERT,      5
# DEFINE HELP,               6
# DEFINE INSERT_TEXT,        7
# DEFINE FIELD_HELP,         8
# DEFINE PAGE_HELP,          9
# DEFINE NAVIGATION,        10
# DEFINE INTERFIELD_CURSOR, 11
# DEFINE NEXT_PAGE,         12
# DEFINE BACK_PAGE,         13
# DEFINE NEXT,              12
# DEFINE BACK,              13
# DEFINE PATH,              14
# DEFINE JUMP,              15
# DEFINE ACTION,            16
# DEFINE FIELD_END,         17
# DEFINE ELEMENT_END,       18
# DEFINE PAGE_END,          19
# DEFINE BYE,               20
# DEFINE LOGON,             21
# DEFINE VIEWPATH,          22
# DEFINE KEYWORD,           23
# DEFINE GUIDE,             24
# DEFINE RECALL,            25
# DEFINE UNDO,              26
# DEFINE WHERE,             27
# DEFINE SRNPRT,            28
# DEFINE SMFILE,            29
# DEFINE SCAN,              30
# DEFINE TOOLS,             31
# DEFINE DIRECTORY,         32
# DEFINE INDEX,             33
# DEFINE FIND,              34
# DEFINE MARK,              34
# DEFINE LEAVE,             35
# DEFINE ZIP,               36
# DEFINE NEW_LINE,          37
# DEFINE SCROLL_UP,         38
# DEFINE SCROLL_DOWN,       39
# DEFINE SET_CLOSE_WINDOW,  40
# DEFINE SET_OPEN_WINDOW,   41
# DEFINE CURSOR,            42
# DEFINE LOGOFF,            43
# DEFINE LOOK,              44
# DEFINE TRAVEL,            45
# DEFINE FIRST_PAGE,        46
# DEFINE LAST_PAGE,         47
# DEFINE PREVIOUS_MENU,     48
# DEFINE LOGICAL_FUNCTIONS, 49
